port:  5000
markdown: kramdown
name: "Oregon Can't Wait"
url: http://findmyreps.datamade.us
encoding: utf-8
timezone: America/Los_Angeles
description: "It’s time to demand action in Salem"
gems:
  - jekyll-redirect-from
google_api_key: AIzaSyDQZgx6BxWj84ZZZwwjgBOI46e0bmLIq5A
